spring.application.name=Producer
brewery-data.stream.key=brewery_stream
image-metadata.stream.key=image_metadata_stream

# Redis Server Properties
spring.data.redis.host=redis
spring.data.redis.port=6379

